# Generated by Django 4.2.8 on 2023-12-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('total_steps', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('steps_list_of_jsons', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tester')),
            ],
        ),
    ]
